### ISSUE TITLE
Says "UNABLE TO LOAD. TAP TO TRY AGAIN."

### ISSUE THREAD

**Issue by TurtleMeds** [JoshHeng/JackboxProxy#3] opened 2023-02-09 17:01 UTC
![Screenshot from 2023-02-09 09-00-35](https://user-images.githubusercontent.com/76972146/217884970-e060a060-736a-4047-b719-40338225ff6a.png)

**Comment by JoshHeng** [comment] 2023-02-09 17:06
Looks like this is being caused by the usage of bundles.jackbox.tv, will look into this later (might be next week)

**Comment by JoshHeng** [comment] 2023-02-09 17:48
This should be fixed @TurtleMeds - could you try it and see if it works?

**Comment by TurtleMeds** [comment] 2023-02-10 04:04
it does! thank you so much

**Closed as completed** 2023-02-10 10:12 UTC
